=== mintchilli/IFT287_tp1/HumanBody.dtd
<?xml version= "1.0" encoding="UTF-8"?>

<!ELEMENT MainBody (Systems,Organs) >
<!ATTLIST MainBody
        bodyName CDATA #REQUIRED
        bodyID CDATA #REQUIRED>

<!ELEMENT Systems (System)*>

<!ELEMENT System (Flow)*>
<!ATTLIST System
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        type CDATA #REQUIRED>

<!ELEMENT Flow (Connectible,Connections)>
<!ATTLIST Flow
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT Connectible (
        Atrium 
        | Ventricle
        | Artery
        | Vein
        | Capillaries
        | Alveoli
        | AirConnectible
        | Nose
        | DeversingDuct
        | StomachTract
        | RectumTract
        | DigestiveTract
        | InnerGallbladder
        | Duct
        | BiDuct
        | DuodenumTract
        | DuctOverflowableJunction
        | SalivaryDuct)*>

<!ELEMENT Atrium EMPTY>
<!ATTLIST Atrium
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT Ventricle EMPTY>
<!ATTLIST Ventricle
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT Artery EMPTY>
<!ATTLIST Artery
        endRadius CDATA #IMPLIED
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        startRadius CDATA #REQUIRED>

<!ELEMENT Vein EMPTY>
<!ATTLIST Vein
        endRadius CDATA #IMPLIED
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        startRadius CDATA #REQUIRED>

<!ELEMENT Capillaries EMPTY>
<!ATTLIST Capillaries
        id CDATA #REQUIRED
        length CDATA #IMPLIED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT Alveoli EMPTY>
<!ATTLIST Alveoli
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT AirConnectible EMPTY>
<!ATTLIST AirConnectible
        endRadius CDATA #REQUIRED
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        startRadius CDATA #REQUIRED>

<!ELEMENT Nose EMPTY>
<!ATTLIST Nose
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT DeversingDuct EMPTY>
<!ATTLIST DeversingDuct
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT StomachTract EMPTY>
<!ATTLIST StomachTract
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT RectumTract EMPTY>
<!ATTLIST RectumTract
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT DigestiveTract EMPTY>
<!ATTLIST DigestiveTract
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT InnerGallbladder EMPTY>
<!ATTLIST InnerGallbladder
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT Duct EMPTY>
<!ATTLIST Duct
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT BiDuct EMPTY>
<!ATTLIST BiDuct
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT DuodenumTract EMPTY>
<!ATTLIST DuodenumTract
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT DuctOverflowableJunction EMPTY>
<!ATTLIST DuctOverflowableJunction
        id CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT SalivaryDuct EMPTY>
<!ATTLIST SalivaryDuct
        id CDATA #REQUIRED
        length CDATA #REQUIRED
        name CDATA #REQUIRED
        volume CDATA #REQUIRED>

<!ELEMENT Connections EMPTY>

<!ELEMENT Organs (Organ)*>

<!ELEMENT Organ EMPTY>
<!ATTLIST Organ
            id CDATA #REQUIRED
            name CDATA #REQUIRED
            systemID CDATA #REQUIRED>

=== mintchilli/IFT287_tp1/HumanBody2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE MainBody SYSTEM "HumanBody.dtd">
<MainBody bodyID="1" bodyName="DrHouse">
  <Systems>
    <System id="0" name="Circulatory" type="0">
      <Flow id="0" name="Heart">
        <Connectible>
          <Atrium id="0" name="Left atrium" volume="120.0"/>
          <Atrium id="1" name="Right atrium" volume="120.0"/>
          <Ventricle id="2" name="Left ventricle" volume="120.0"/>
          <Ventricle id="3" name="Right ventricle" volume="120.0"/>
        </Connectible>
        <Connections/>
      </Flow>
      <Flow id="1" name="Aorta connection">
        <Connectible>
          <Artery endRadius="1.4" id="0" length="3.0" name="Ascending aorta" startRadius="1.3"/>
          <Artery endRadius="1.6" id="1" length="3.0" name="Arch of the aorta" startRadius="1.4"/>
        </Connectible>
        <Connections/>
      </Flow>
      <Flow id="2" name="Coronary">
        <Connectible>
          <Vein endRadius="0.271109" id="5" length="6.0" name="Middle cardiac" startRadius="0.271109"/>
          <Vein endRadius="0.271109" id="6" length="6.0" name="Great cardiac" startRadius="0.271109"/>
          <Vein endRadius="0.156525" id="7" length="3.0" name="Anterior cardiac" startRadius="0.156525"/>
          <Vein endRadius="0.156525" id="8" length="3.0" name="Small cardiac" startRadius="0.156525"/>
          <Vein endRadius="0.22136" id="9" length="3.0" name="Great anterior" startRadius="0.22136"/>
          <Vein endRadius="0.313049" id="10" length="1.0" name="Coronary sinus" startRadius="0.313049"/>
          <Artery endRadius="0.271109" id="0" length="4.0" name="Left coronary" startRadius="0.271109"/>
          <Artery endRadius="0.156525" id="1" length="4.0" name="Right coronary" startRadius="0.156525"/>
          <Artery endRadius="0.156525" id="2" length="3.0" name="Posterior inter ventricular" startRadius="0.156525"/>
          <Artery endRadius="0.191703" id="3" length="3.0" name="Anterior inter ventricular" startRadius="0.191703"/>
          <Artery endRadius="0.191703" id="4" length="3.0" name="Circumflex" startRadius="0.191703"/>
          <Capillaries id="11" name="Left heart" volume="100.0"/>
          <Capillaries id="12" name="Right heart" volume="100.0"/>
        </Connectible>
        <Connections/>
      </Flow>
      <Flow id="3" name="Pulmonary">
        <Connectible>
          <Vein id="3" length="7.0" name="Right pulmonary 1" startRadius="1.0606"/>
          <Vein id="4" length="7.0" name="Right pulmonary 2" startRadius="1.0606"/>
          <Vein id="5" length="7.0" name="Left pulmonary 1" startRadius="1.0606"/>
          <Vein id="6" length="7.0" name="Left pulmonary 2" startRadius="1.0606"/>
          <Artery endRadius="1.5" id="0" length="6.0" name="Pulmonary trunk" startRadius="1.5"/>
          <Artery id="1" length="6.0" name="Right pulmonary" startRadius="1.0606"/>
          <Artery id="2" length="6.0" name="Left pulmonary" startRadius="1.0606"/>
          <Capillaries id="7" name="Left alveoli" volume="120.0"/>
          <Capillaries id="8" name="Right alveoli" volume="120.0"/>
        </Connectible>
        <Connections/>
      </Flow>
      <Flow id="4" name="Head and thoracic">
        <Connectible>
          <Vein id="33" length="1.0" name="Right superior thyroid" startRadius="0.005"/>
          <Vein id="34" length="1.0" name="Left superior thyroid" startRadius="0.005"/>
          <Vein id="35" length="1.0" name="Right internal jugular" startRadius="0.055"/>
          <Vein id="36" length="1.0" name="Left internal jugular" startRadius="0.055"/>
          <Vein id="37" length="1.0" name="Right facial" startRadius="0.005"/>
          <Vein id="38" length="1.0" name="Left facial" startRadius="0.005"/>
          <Vein id="39" length="1.0" name="Right lingual" startRadius="0.005"/>
          <Vein id="40" length="1.0" name="Left lingual" startRadius="0.005"/>
          <Vein id="41" length="1.0" name="Right occipital" startRadius="0.015"/>
          <Vein id="42" length="1.0" name="Left occipital" startRadius="0.015"/>
          <Vein id="43" length="1.0" name="Right superficial temporal" startRadius="0.01"/>
          <Vein id="44" length="1.0" name="Left superficial temporal" startRadius="0.01"/>
          <Vein id="45" length="1.0" name="Right maxillary" startRadius="0.005"/>
          <Vein id="46" length="1.0" name="Left maxillary" startRadius="0.005"/>
          <Vein id="47" length="1.0" name="Right external jugular" startRadius="0.04"/>
          <Vein id="48" length="1.0" name="Left external jugular" startRadius="0.04"/>
          <Vein id="49" length="1.0" name="Right internal thoracic" startRadius="0.02"/>
          <Vein id="50" length="1.0" name="Left internal thoracic" startRadius="0.02"/>
          <Vein id="51" length="1.0" name="Right vertebral" startRadius="0.01"/>
          <Vein id="52" length="1.0" name="Left vertebral" startRadius="0.01"/>
          <Vein id="53" length="1.0" name="Azygos" startRadius="0.055"/>
          <Vein id="54" length="1.0" name="Hemiazygos" startRadius="0.01"/>
          <Vein id="55" length="1.0" name="Bronchial" startRadius="0.01"/>
          <Vein id="56" length="1.0" name="Esophageal" startRadius="0.01"/>
          <Vein id="57" length="1.0" name="Pericardial" startRadius="0.015"/>
          <Vein id="58" length="1.0" name="Right brachiocephalic" startRadius="0.205"/>
          <Vein id="59" length="1.0" name="Left brachiocephalic" startRadius="0.205"/>
          <Artery id="0" length="1.0" name="Left subclavian" startRadius="0.15"/>
          <Artery id="1" length="1.0" name="Left common carotid" startRadius="0.075"/>
          <Artery id="2" length="2.25" name="Brachiocephalic" startRadius="0.225"/>
          <Artery id="3" length="13.0" name="Thoracic aorta" startRadius="1.25"/>
          <Artery id="4" length="1.0" name="Right subclavian" startRadius="0.15"/>
          <Artery id="5" length="1.0" name="Right common carotid" startRadius="0.075"/>
          <Artery id="6" length="1.0" name="Right internal thoracic" startRadius="0.02"/>
          <Artery id="7" length="1.0" name="Right posterior intercostal" startRadius="0.01"/>
          <Artery id="8" length="1.0" name="Right vertebral" startRadius="0.03"/>
          <Artery id="9" length="1.0" name="Left internal thoracic" startRadius="0.02"/>
          <Artery id="10" length="1.0" name="Left posterior intercostal" startRadius="0.01"/>
          <Artery id="11" length="1.0" name="Left vertebral" startRadius="0.03"/>
          <Artery id="12" length="1.0" name="Basilar" startRadius="0.04"/>
          <Artery id="13" length="1.0" name="Right internal carotid" startRadius="0.03"/>
          <Artery id="14" length="1.0" name="Left internal carotid" startRadius="0.03"/>
          <Artery id="15" length="1.0" name="Right superior thyroid" startRadius="0.005"/>
          <Artery id="16" length="1.0" name="Left superior thyroid" startRadius="0.005"/>
          <Artery id="17" length="1.0" name="Right facial" startRadius="0.005"/>
          <Artery id="18" length="1.0" name="Left facial" startRadius="0.005"/>
          <Artery id="19" length="1.0" name="Right lingual" startRadius="0.005"/>
          <Artery id="20" length="1.0" name="Left lingual" startRadius="0.005"/>
          <Artery id="21" length="1.0" name="Right external carotid" startRadius="0.03"/>
          <Artery id="22" length="1.0" name="Left external carotid" startRadius="0.03"/>
          <Artery id="23" length="1.0" name="Right superficial temporal" startRadius="0.015"/>
          <Artery id="24" length="1.0" name="Left superficial temporal" startRadius="0.015"/>
          <Artery id="25" length="1.0" name="Right maxillary" startRadius="0.005"/>
          <Artery id="26" length="1.0" name="Left maxillary" startRadius="0.005"/>
          <Artery id="27" length="1.0" name="Right occipital" startRadius="0.015"/>
          <Artery id="28" length="1.0" name="Left occipital" startRadius="0.015"/>
          <Artery id="29" length="1.0" name="Bronchial" startRadius="0.01"/>
          <Artery id="30" length="1.0" name="Esophageal" startRadius="0.01"/>
          <Artery id="31" length="1.0" name="Right superior phrenic" startRadius="0.005"/>
          <Artery id="32" length="1.0" name="Left superior phrenic" startRadius="0.005"/>
          <Capillaries id="60" length="1.0" name="Brain" volume="0.1"/>
          <Capillaries id="61" length="1.0" name="Thyroid" volume="0.01"/>
          <Capillaries id="62" length="1.0" name="Facial" volume="0.01"/>
          <Capillaries id="63" length="1.0" name="Lingual" volume="0.01"/>
          <Capillaries id="64" length="1.0" name="Head" volume="0.05"/>
          <Capillaries id="65" length="1.0" name="Maxilary" volume="0.01"/>
          <Capillaries id="66" length="1.0" name="Vertebral" volume="0.02"/>
          <Capillaries id="67" length="1.0" name="Right costal" volume="0.03"/>
          <Capillaries id="68" length="1.0" name="Left costal" volume="0.03"/>
          <Capillaries id="69" length="1.0" name="Lung" volume="0.01"/>
          <Capillaries id="70" length="1.0" name="Esophageal" volume="0.01"/>
          <Capillaries id="71" length="1.0" name="Diaphragm" volume="0.015"/>
        </Connectible>
        <Connections/>
      </Flow>
      <Flow id="5" name="Left arm">
        <Connectible>
          <Vein id="6" length="1.0" name="Basilic" startRadius="0.035"/>
          <Vein id="7" length="1.0" name="Cephalic" startRadius="0.015"/>
          <Vein id="8" length="1.0" name="Ulnar" startRadius="0.015"/>
          <Vein id="9" length="1.0" name="Radial" startRadius="0.015"/>
          <Vein id="10" length="1.0" name="Brachial" startRadius="0.045"/>
          <Vein id="11" length="1.0" name="Axillary" startRadius="0.1"/>
          <Vein id="12" length="1.0" name="Subclavian" startRadius="0.1"/>
          <Artery id="0" length="1.0" name="Axillary" startRadius="0.1"/>
